DROP TABLE pacientes CASCADE;
DROP TABLE especialistas CASCADE;
DROP TABLE comidas CASCADE;
DROP TABLE alimentos CASCADE;
DROP TABLE a_c CASCADE;


TRUNCATE TABLE pacientes CASCADE;
TRUNCATE TABLE especialistas CASCADE;
TRUNCATE TABLE comidas CASCADE;
TRUNCATE TABLE alimentos CASCADE;
TRUNCATE TABLE a_c CASCADE;